name: CI Meson

on: 
  workflow_dispatch: 


  
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
  pull_request:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Install Package
  # You may pin to the exact commit or the version.
  # uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30
        uses: ConorMacBride/install-package@v1.1.0
        with:
    # Packages to install with brew on macOS
          brew: glfw #optional, default is 
    # Packages to install with brew cask on macOS
          brew-cask:  glfw # optional, default is 
    # Packages to install with apt on Linux
          apt: libglfw3-dev
    # optional, default is 
    # Packages to install with choco on Windows
          choco: glfw3 # optional, default is 
          
      - name: Configure Project
        run: meson setup builddir/
        env:
          CC: gcc
      - name: Run Tests
        run: meson test -C builddir/ -v
      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
